#!name=Shadowrocket Policy Module
#!desc=Route normal traffic, YouTube, Netflix, and direct traffic to separate policies.
#!author=hainingshen
#!homepage=https://github.com/hainingshen/shadowrocket-policy-module
#!date=2026-06-30

[Rule]

# youtube.list -> YouTube
DOMAIN-SUFFIX,youtube.com,YouTube
DOMAIN-SUFFIX,youtu.be,YouTube
DOMAIN-SUFFIX,yt.be,YouTube
DOMAIN-SUFFIX,ytimg.com,YouTube
DOMAIN-SUFFIX,googlevideo.com,YouTube
DOMAIN-SUFFIX,youtube-nocookie.com,YouTube
DOMAIN-SUFFIX,youtubeeducation.com,YouTube
DOMAIN-SUFFIX,youtubegaming.com,YouTube
DOMAIN-SUFFIX,youtubekids.com,YouTube
DOMAIN-SUFFIX,youtubei.googleapis.com,YouTube
DOMAIN-SUFFIX,ggpht.com,YouTube
DOMAIN-SUFFIX,withyoutube.com,YouTube

# netflix.list -> Netflix
DOMAIN-SUFFIX,netflix.com,Netflix
DOMAIN-SUFFIX,netflix.net,Netflix
DOMAIN-SUFFIX,netflixdnstest0.com,Netflix
DOMAIN-SUFFIX,netflixdnstest1.com,Netflix
DOMAIN-SUFFIX,netflixdnstest2.com,Netflix
DOMAIN-SUFFIX,netflixdnstest3.com,Netflix
DOMAIN-SUFFIX,netflixdnstest4.com,Netflix
DOMAIN-SUFFIX,netflixdnstest5.com,Netflix
DOMAIN-SUFFIX,netflixdnstest6.com,Netflix
DOMAIN-SUFFIX,netflixdnstest7.com,Netflix
DOMAIN-SUFFIX,netflixdnstest8.com,Netflix
DOMAIN-SUFFIX,netflixdnstest9.com,Netflix
DOMAIN-SUFFIX,nflxext.com,Netflix
DOMAIN-SUFFIX,nflximg.com,Netflix
DOMAIN-SUFFIX,nflximg.net,Netflix
DOMAIN-SUFFIX,nflxso.net,Netflix
DOMAIN-SUFFIX,nflxvideo.net,Netflix
DOMAIN-SUFFIX,nflxsearch.net,Netflix

# direct.list -> DIRECT
DOMAIN-SUFFIX,local,DIRECT
DOMAIN-SUFFIX,lan,DIRECT
IP-CIDR,0.0.0.0/8,DIRECT,no-resolve
IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
IP-CIDR,169.254.0.0/16,DIRECT,no-resolve
IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
IP-CIDR,224.0.0.0/4,DIRECT,no-resolve
IP-CIDR,240.0.0.0/4,DIRECT,no-resolve
IP-CIDR6,::1/128,DIRECT,no-resolve
IP-CIDR6,fc00::/7,DIRECT,no-resolve
IP-CIDR6,fe80::/10,DIRECT,no-resolve
DOMAIN-SUFFIX,cn,DIRECT
DOMAIN-SUFFIX,alibaba.com,DIRECT
DOMAIN-SUFFIX,alicdn.com,DIRECT
DOMAIN-SUFFIX,aliyun.com,DIRECT
DOMAIN-SUFFIX,aliyuncs.com,DIRECT
DOMAIN-SUFFIX,baidu.com,DIRECT
DOMAIN-SUFFIX,bdstatic.com,DIRECT
DOMAIN-SUFFIX,bilibili.com,DIRECT
DOMAIN-SUFFIX,bilivideo.com,DIRECT
DOMAIN-SUFFIX,bytedance.com,DIRECT
DOMAIN-SUFFIX,byteimg.com,DIRECT
DOMAIN-SUFFIX,douyin.com,DIRECT
DOMAIN-SUFFIX,jd.com,DIRECT
DOMAIN-SUFFIX,mi.com,DIRECT
DOMAIN-SUFFIX,miui.com,DIRECT
DOMAIN-SUFFIX,netease.com,DIRECT
DOMAIN-SUFFIX,qq.com,DIRECT
DOMAIN-SUFFIX,qpic.cn,DIRECT
DOMAIN-SUFFIX,sina.com,DIRECT
DOMAIN-SUFFIX,sinaimg.cn,DIRECT
DOMAIN-SUFFIX,taobao.com,DIRECT
DOMAIN-SUFFIX,tencent.com,DIRECT
DOMAIN-SUFFIX,tmall.com,DIRECT
DOMAIN-SUFFIX,wechat.com,DIRECT
DOMAIN-SUFFIX,weixin.qq.com,DIRECT
DOMAIN-SUFFIX,xiaomi.com,DIRECT
DOMAIN,captive.apple.com,DIRECT
DOMAIN-SUFFIX,apple.com.cn,DIRECT
GEOIP,CN,DIRECT

# Default proxy policy.
FINAL,General
