#!MANAGED-CONFIG https://raw.githubusercontent.com/hainingshen/shadowrocket-policy-module/main/configs/auto-policy.conf interval=86400 strict=false

[General]
update-url = https://raw.githubusercontent.com/hainingshen/shadowrocket-policy-module/main/configs/auto-policy.conf
bypass-system = true
skip-proxy = 127.0.0.1, localhost, *.local, captive.apple.com
dns-server = system, 223.5.5.5, 119.29.29.29, 8.8.8.8, 1.1.1.1
ipv6 = false

[Proxy Group]
# These groups automatically include manually added nodes and subscription nodes.
General = select,url=http://www.gstatic.com/generate_204,interval=86400,timeout=5,select=0,policy-regex-filter=.*
YouTube = select,General,DIRECT,url=http://www.gstatic.com/generate_204,interval=86400,timeout=5,select=0,policy-regex-filter=.*
Netflix = select,General,DIRECT,url=http://www.gstatic.com/generate_204,interval=86400,timeout=5,select=0,policy-regex-filter=.*

[Rule]
RULE-SET,https://raw.githubusercontent.com/hainingshen/shadowrocket-policy-module/main/rules/youtube.list,YouTube
RULE-SET,https://raw.githubusercontent.com/hainingshen/shadowrocket-policy-module/main/rules/generated/youtube.list,YouTube
RULE-SET,https://raw.githubusercontent.com/hainingshen/shadowrocket-policy-module/main/rules/netflix.list,Netflix
RULE-SET,https://raw.githubusercontent.com/hainingshen/shadowrocket-policy-module/main/rules/generated/netflix.list,Netflix
RULE-SET,https://raw.githubusercontent.com/hainingshen/shadowrocket-policy-module/main/rules/china-im.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/hainingshen/shadowrocket-policy-module/main/rules/generated/china-im.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/hainingshen/shadowrocket-policy-module/main/rules/general.list,General
RULE-SET,https://raw.githubusercontent.com/hainingshen/shadowrocket-policy-module/main/rules/generated/general.list,General
RULE-SET,https://raw.githubusercontent.com/hainingshen/shadowrocket-policy-module/main/rules/generated/direct.list,DIRECT
GEOIP,CN,DIRECT
FINAL,General
