from __future__ import annotations

from pathlib import Path
import json
import sys
import urllib.request


SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from rulelib import (
    Rule,
    parse_cidr_list_line,
    parse_domain_list_line,
    parse_payload_line,
    parse_rule_line,
)


ROOT = Path(__file__).resolve().parents[1]
SOURCES = ROOT / "config" / "sources.json"
GENERATED_DIR = ROOT / "rules" / "generated"
REPORT = ROOT / "reports" / "sources.md"
POLICY_FILENAMES = {
    "YouTube": "youtube.list",
    "Netflix": "netflix.list",
    "ChinaIM": "china-im.list",
    "DIRECT": "direct.list",
    "General": "general.list",
}


def fetch_text(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": "shadowrocket-policy-module"})
    with urllib.request.urlopen(request, timeout=45) as response:
        charset = response.headers.get_content_charset() or "utf-8"
        return response.read().decode(charset, errors="replace")


def parse_source(text: str, source_format: str) -> list[Rule]:
    rules: list[Rule] = []
    parsers = {
        "cidr-list": parse_cidr_list_line,
        "domain-list": parse_domain_list_line,
        "geosite": parse_domain_list_line,
        "payload": parse_payload_line,
        "rules": parse_rule_line,
    }
    parser = parsers[source_format]

    for line in text.splitlines():
        rule = parser(line)
        if rule is not None:
            rules.append(rule)
    return rules


def filter_rules(source: dict, rules: list[Rule]) -> list[Rule]:
    include_types = {rule_type.upper() for rule_type in source.get("include_types", [])}
    exclude_types = {rule_type.upper() for rule_type in source.get("exclude_types", [])}
    exclude_values = {value.lower() for value in source.get("exclude_values", [])}
    exclude_rules = {
        tuple(part.strip().lower() for part in rule.split(",", 1))
        for rule in source.get("exclude_rules", [])
        if "," in rule
    }

    filtered: list[Rule] = []
    for rule in rules:
        if include_types and rule.rule_type not in include_types:
            continue
        if rule.rule_type in exclude_types:
            continue
        if rule.value.lower() in exclude_values:
            continue
        if (rule.rule_type.lower(), rule.value.lower()) in exclude_rules:
            continue
        filtered.append(rule)
    min_kept = source.get("min_kept")
    if min_kept is not None and len(filtered) < int(min_kept):
        raise ValueError(
            f"{source['name']} kept {len(filtered)} rules, expected at least {min_kept}"
        )
    return filtered


def compress_domain_rules(rules: list[Rule]) -> list[Rule]:
    suffixes = {rule.value for rule in rules if rule.rule_type == "DOMAIN-SUFFIX"}
    if not suffixes:
        return rules

    compressed: list[Rule] = []
    for rule in rules:
        if rule.rule_type not in {"DOMAIN", "DOMAIN-SUFFIX"}:
            compressed.append(rule)
            continue
        if is_covered_by_parent_suffix(rule.value, suffixes):
            continue
        compressed.append(rule)
    return compressed


def is_covered_by_parent_suffix(value: str, suffixes: set[str]) -> bool:
    labels = value.split(".")
    for index in range(1, len(labels)):
        parent = ".".join(labels[index:])
        if parent in suffixes:
            return True
    return False


def render_generated_file(policy: str, entries: list[tuple[dict, list[Rule]]]) -> str:
    lines = [
        f"# Generated rules for {policy}.",
        "# Do not edit this file directly; edit config/sources.json or rules/*.list instead.",
        "",
    ]

    seen: set[str] = set()
    for source, rules in entries:
        lines.append(f"# Source: {source['name']}")
        lines.append(f"# URL: {source['url']}")
        source_count = 0
        for rule in rules:
            if rule.key in seen:
                continue
            seen.add(rule.key)
            source_count += 1
            lines.append(rule.render_without_policy())
        lines.append(f"# Source count after policy-level dedupe: {source_count}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def render_report(stats: list[dict]) -> str:
    lines = [
        "# Rule Source Report",
        "",
        "This report is generated from `config/sources.json` by `scripts/update_rules.py`.",
        "",
        "| Policy | Source | Parsed | Kept | Added | URL |",
        "| --- | --- | ---: | ---: | ---: | --- |",
    ]
    for stat in stats:
        lines.append(
            "| {policy} | {name} | {parsed} | {kept} | {added} | {url} |".format(
                policy=stat["policy"],
                name=stat["name"],
                parsed=stat["parsed"],
                kept=stat["kept"],
                added=stat["added"],
                url=stat["url"],
            )
        )
    return "\n".join(lines) + "\n"


def update_policy(policy: str, sources: list[dict], stats: list[dict]) -> None:
    entries: list[tuple[dict, list[Rule]]] = []
    policy_seen: set[str] = set()

    for source in sources:
        text = fetch_text(source["url"])
        parsed = parse_source(text, source.get("format", "rules"))
        filtered = filter_rules(source, parsed)
        added = 0
        unique_rules: list[Rule] = []
        for rule in filtered:
            if rule.key in policy_seen:
                continue
            policy_seen.add(rule.key)
            unique_rules.append(rule)
            added += 1
        entries.append((source, compress_domain_rules(unique_rules)))
        stats.append(
            {
                "policy": policy,
                "name": source["name"],
                "url": source["url"],
                "parsed": len(parsed),
                "kept": len(filtered),
                "added": added,
            }
        )

    output = GENERATED_DIR / POLICY_FILENAMES[policy]
    output.write_text(render_generated_file(policy, entries), encoding="utf-8", newline="\n")
    print(f"Wrote {output.relative_to(ROOT)}")


def main() -> None:
    config = json.loads(SOURCES.read_text(encoding="utf-8"))
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    REPORT.parent.mkdir(parents=True, exist_ok=True)

    stats: list[dict] = []
    for policy, sources in config["policies"].items():
        update_policy(policy, sources, stats)

    REPORT.write_text(render_report(stats), encoding="utf-8", newline="\n")
    print(f"Wrote {REPORT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
